#############################################################################
# Makefile for building: qt_kj_main.app/Contents/MacOS/qt_kj_main
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  qt_kj_main.pro
# Template: app
# Command: /Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qt_kj_main.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_XLSX_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang -I. -I../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework QtXlsx -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		connectdb.cpp \
		index.cpp \
		login.cpp \
		user.cpp \
		datatrans.cpp \
		dynamicarray.cpp qrc_kj.cpp \
		moc_mainwindow.cpp \
		moc_index.cpp \
		moc_login.cpp \
		moc_user.cpp \
		moc_datatrans.cpp
OBJECTS       = main.o \
		mainwindow.o \
		connectdb.o \
		index.o \
		login.o \
		user.o \
		datatrans.o \
		dynamicarray.o \
		qrc_kj.o \
		moc_mainwindow.o \
		moc_index.o \
		moc_login.o \
		moc_user.o \
		moc_datatrans.o
DIST          = ../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		qt_kj_main.pro \
		kj.qrc \
		qt_kj_main.pro
QMAKE_TARGET  = qt_kj_main
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qt_kj_main.app/Contents/MacOS/qt_kj_main

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile qt_kj_main.app/Contents/PkgInfo qt_kj_main.app/Contents/Resources/empty.lproj qt_kj_main.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_index.h ui_login.h ui_user.h ui_datatrans.h $(OBJECTS)  
	@test -d qt_kj_main.app/Contents/MacOS/ || mkdir -p qt_kj_main.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_kj_main.pro ../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		qt_kj_main.pro \
		kj.qrc \
		/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/QtXlsx.prl \
		/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/QtSql.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qt_kj_main.pro
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf:
qt_kj_main.pro:
kj.qrc:
/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/QtXlsx.prl:
/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/QtSql.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile qt_kj_main.pro

qmake_all: FORCE

qt_kj_main.app/Contents/PkgInfo: 
	@test -d qt_kj_main.app/Contents || mkdir -p qt_kj_main.app/Contents
	@$(DEL_FILE) qt_kj_main.app/Contents/PkgInfo
	@echo "APPL????" >qt_kj_main.app/Contents/PkgInfo
qt_kj_main.app/Contents/Resources/empty.lproj: 
	@test -d qt_kj_main.app/Contents/Resources || mkdir -p qt_kj_main.app/Contents/Resources
	@touch qt_kj_main.app/Contents/Resources/empty.lproj
	
qt_kj_main.app/Contents/Info.plist: 
	@test -d qt_kj_main.app/Contents || mkdir -p qt_kj_main.app/Contents
	@$(DEL_FILE) qt_kj_main.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.qt_kj_main,g" -e "s,@EXECUTABLE@,qt_kj_main,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/Info.plist.app >qt_kj_main.app/Contents/Info.plist
dist: 
	@test -d .tmp/qt_kj_main1.0.0 || mkdir -p .tmp/qt_kj_main1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt_kj_main1.0.0/ && $(COPY_FILE) --parents kj.qrc .tmp/qt_kj_main1.0.0/ && $(COPY_FILE) --parents mainwindow.h connectdb.h index.h login.h user.h datatrans.h dynamicarray.h .tmp/qt_kj_main1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp connectdb.cpp index.cpp login.cpp user.cpp datatrans.cpp dynamicarray.cpp .tmp/qt_kj_main1.0.0/ && $(COPY_FILE) --parents mainwindow.ui index.ui login.ui user.ui datatrans.ui .tmp/qt_kj_main1.0.0/ && (cd `dirname .tmp/qt_kj_main1.0.0` && $(TAR) qt_kj_main1.0.0.tar qt_kj_main1.0.0 && $(COMPRESS) qt_kj_main1.0.0.tar) && $(MOVE) `dirname .tmp/qt_kj_main1.0.0`/qt_kj_main1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt_kj_main1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r qt_kj_main.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_kj.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_kj.cpp
qrc_kj.cpp: kj.qrc \
		qrc/image/icon.png \
		qrc/image/sort_icon.png \
		qrc/image/face.png \
		qrc/image/delete_icon.png \
		qrc/image/save.png \
		qrc/image/compute_icon.png \
		qrc/image/temperature.png \
		qrc/image/modify_icon.png \
		qrc/image/open.png \
		qrc/image/data_icon.png \
		qrc/image/new.png \
		qrc/image/cut.png \
		qrc/image/gotocell.png \
		qrc/image/passwd_icon.png \
		qrc/image/copy.png \
		qrc/image/find.png \
		qrc/image/insert_icon.png \
		qrc/image/save_icon.png \
		qrc/image/print_icon.png \
		qrc/image/exit_icon.png \
		qrc/image/paste.png
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/rcc -name kj kj.qrc -o qrc_kj.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_index.cpp moc_login.cpp moc_user.cpp moc_datatrans.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_index.cpp moc_login.cpp moc_user.cpp moc_datatrans.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		connectdb.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		index.h \
		ui_index.h \
		datatrans.h \
		ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QStandardItemModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		dynamicarray.h \
		mainwindow.h
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_index.cpp: ../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_index.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		index.h
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) index.h -o moc_index.cpp

moc_login.cpp: ../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_login.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		mainwindow.h \
		ui_mainwindow.h \
		connectdb.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		user.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		index.h \
		ui_index.h \
		datatrans.h \
		ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QStandardItemModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		dynamicarray.h \
		login.h
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) login.h -o moc_login.cpp

moc_user.cpp: ../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		user.h
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) user.h -o moc_user.cpp

moc_datatrans.cpp: ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		datatrans.h
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) datatrans.h -o moc_datatrans.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_index.h ui_login.h ui_user.h ui_datatrans.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_index.h ui_login.h ui_user.h ui_datatrans.h
ui_mainwindow.h: mainwindow.ui
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_index.h: index.ui
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/uic index.ui -o ui_index.h

ui_login.h: login.ui
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/uic login.ui -o ui_login.h

ui_user.h: user.ui
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/uic user.ui -o ui_user.h

ui_datatrans.h: datatrans.ui
	/Users/r0b1n/Qt5.2.1/5.2.1/clang_64/bin/uic datatrans.ui -o ui_datatrans.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp connectdb.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		mainwindow.h \
		ui_mainwindow.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		index.h \
		ui_index.h \
		datatrans.h \
		ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QStandardItemModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		dynamicarray.h \
		login.h \
		ui_login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp login.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_login.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		mainwindow.h \
		ui_mainwindow.h \
		connectdb.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		user.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		index.h \
		ui_index.h \
		datatrans.h \
		ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QStandardItemModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		dynamicarray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDataWidgetMapper \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		kjanalysis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

connectdb.o: connectdb.cpp ../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectdb.o connectdb.cpp

index.o: index.cpp ../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRecord \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o index.o index.cpp

login.o: login.cpp ../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRecord \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		index.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		ui_index.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqltablemodel.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRelationalTableModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrelationaltablemodel.h \
		user.h \
		ui_user.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQueryModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquerymodel.h \
		mainwindow.h \
		ui_mainwindow.h \
		connectdb.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		datatrans.h \
		ui_datatrans.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxdocument.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QtGlobal \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxformat.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QFont \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QExplicitlySharedDataPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QVariant \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxworksheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractsheet.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxabstractooxmlfile.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcell.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellrange.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtXlsx.framework/Versions/0/Headers/xlsxcellreference.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QMap \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointF \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/QStandardItemModel \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		dynamicarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

user.o: user.cpp ../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRecord \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

datatrans.o: datatrans.cpp ../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlRecord \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlrecord.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datatrans.o datatrans.cpp

dynamicarray.o: dynamicarray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dynamicarray.o dynamicarray.cpp

qrc_kj.o: qrc_kj.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_kj.o qrc_kj.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_index.o: moc_index.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_index.o moc_index.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_user.o: moc_user.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_user.o moc_user.cpp

moc_datatrans.o: moc_datatrans.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datatrans.o moc_datatrans.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

